### ISSUE TITLE
TraveltoLightSourceGoal lag

### ISSUE THREAD

**Issue by dogonotoughen** [DakotaPride/Pride-Moths#7] opened 2024-09-26 10:31 UTC
**Describe The Issue**
1.20.1 Neoforge | Mod version "pridemoths-1.8.3+1.20.1"

**Steps To Reproduce**
[Provide The Potential Steps To Reproduce The Issue]
1. Install the mod and run Minecraft
2. run Spark Profiler

**Screenshots**
![image](https://github.com/user-attachments/assets/9bb3b630-0b3b-4282-9637-5cb88859a889)

**Comment by DakotaPride** [comment] 2024-09-26 12:05
Do you know perhaps how many moths were spawned during this period? It's alright if not, just would make it (somewhat) easier to test it and make sure that the issue is actually fixed.

**Comment by DakotaPride** [comment] 2024-10-06 14:44
Should be fixed now, let me know if you still come across this issue or other issues!

**Closed as completed by DakotaPride** 2024-10-06 14:44 UTC
Labels: bug
